# ==================================
# Configuración Básica del Blog
# ==================================
title: Mi Blog Personal
email: tu-email@ejemplo.com
description: >-
  El lugar donde escribo sobre tecnología, desarrollo y mis proyectos.
baseurl: "/blog"
url: "https://agussvgomez.github.io"

# ==================================
# Configuración del Tema
# ==================================
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# ==================================
# Configuración de Google Analytics
# ==================================
google_analytics: G-XXXXXXXXXX
