# ==================================
# Configuración Básica del Blog
# ==================================
title: Mi Blog Personal
email: tu-email@ejemplo.com
description: >- # Descripción que aparecerá en los motores de búsqueda
  El lugar donde escribo sobre tecnología, desarrollo y mis proyectos.
baseurl: "/blog" # <--- CAMBIA ESTO: Debe ser el nombre de tu repositorio
url: "https://agussvgomez.github.io" # <--- CAMBIA ESTO: Tu dominio principa

# ==================================
# Configuración del Tema
# ==================================
# Aquí definimos el tema. Usaremos 'minimal' como ejemplo.
theme: pages-themes/cayman 
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# ==================================
# Configuración de Google Analytics
# ==================================
# Reemplaza G-XXXXXXXXXX con tu ID de Google Analytics
google_analytics: G-XXXXXXXXXX
